apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwater-app-github
  labels:
    app: octopus-underwater-app
spec:
  selector:
    matchLabels:
        app: octopus-underwater-app
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: octopus-underwater-app
    spec:
      containers:
        - name: octopus-underwater-app
          image: 640262166032.dkr.ecr.ap-south-1.amazonaws.com/weather_app:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
